version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kalsash/backend-for-lab2ai:latest  
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - OLLAMA_BASE_URL=http://host.docker.internal:11434/ 
      - ConnectionStrings__DefaultConnection=Host=db;Database=MoviesDB;Username=postgres;Password=1234;Port=5432
    depends_on:
      - db
    volumes:
      - ./MoviesData.json:/app/MoviesData.json
      - embeddings_cache:/app/EmbeddingsCache  
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg16  
    environment:
      - POSTGRES_DB=MoviesDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:  
  embeddings_cache: